[package]
name = "prometheus-macros"
descrption = "Declare and compose metrics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prometheus = { version = "0.13",  default-feature = false}
